#!/usr/bin/env python3.2
from itertools import product
from math import floor
from pygame import Color
import game
import gol
import pygame


class GoL(game.PyGame):
    gol = None
    origin = (0, 0)
    cell_size = 10
    generate = False

    def __init__(self):
        game.PyGame.__init__(self, (0, 0), 'Game of Life')
        self.gol = gol.GameOfLife()

    def init(self):
        pass

    def update(self):
        if self.generate:
            self.gol.next_state()
        # fill background
        self.window.fill(Color('#cccccc'))
        # mark origin
        pygame.draw.line(self.window, Color('#c00303'),
                         (self.origin[0], self.origin[1] - self.cell_size),
                         (self.origin[0], self.origin[1] + self.cell_size),
                         int(self.cell_size / 3) or 1)
        pygame.draw.line(self.window, Color('#c00303'),
                         (self.origin[0] - self.cell_size, self.origin[1]),
                         (self.origin[0] + self.cell_size, self.origin[1]),
                         int(self.cell_size / 3) or 1)
        # draw cells
        o_cell = self.get_cell_from_pos((0, 0))
        dims_cell = self.get_cell_from_pos(self.dims)
        x_range = (o_cell[0], dims_cell[0])
        y_range = (o_cell[1], dims_cell[1])
        for x, y in product(range(*x_range), range(*y_range)):
            if self.gol.is_alive(x, y):
                pos = self.get_pos_from_cell((x, y))
                rect = (pos[0], pos[1], self.cell_size, self.cell_size)
                pygame.draw.rect(self.window, Color('#333333'), rect)

    def on_mouse_down(self, event):
        if event.button == 1:
            cell = self.get_cell_from_pos(event.pos)
            if self.gol.is_alive(*cell):
                self.gol.current_state.remove(cell)
            else:
                self.gol.current_state.add(cell)
        elif event.button == 4:
            self.size_up()
        elif event.button == 5:
            self.size_down()

    def on_mouse_up(self, event):
        pass

    def on_mouse_move(self, event):
        if event.buttons == (0, 1, 0):
            self.origin = tuple([o + r for o, r
                                 in zip(self.origin, event.rel)])

    def on_key_down(self, event):
        if event.unicode == 'p':
            self.generate = not self.generate
        elif event.unicode == 's':
            if not self.generate:
                self.gol.next_state()
        elif event.unicode == 'c':
            self.gol.set_state([])
        elif event.unicode == '+':
            self.size_up()
        elif event.unicode == '-':
            self.size_down()
        elif event.unicode == 'q':
            self.stop()

    def on_resize(self, event):
        self.dims = event.size
        self.window = pygame.display.set_mode(
            self.dims, pygame.RESIZABLE | pygame.DOUBLEBUF)

    def size_up(self):
        self.cell_size = int(self.cell_size * 2)

    def size_down(self):
        self.cell_size = int(self.cell_size / 2 if self.cell_size > 8 else 4)

    def get_cell_from_pos(self, pos):
        return tuple([int(floor((p - o) / self.cell_size))
                      for p, o in zip(pos, self.origin)])

    def get_pos_from_cell(self, cell):
        return tuple([c * self.cell_size + o
                      for c, o in zip(cell, self.origin)])


if __name__ == '__main__':
    g = GoL()
    g.start()
